# Etape 1: Construire l'application Angular pour la production
FROM node:18 AS build-stage
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npx ng build --configuration=production

# Etape 2: Servir l'application avec Nginx
FROM nginx:alpine
COPY --from=build-stage /app/dist/web/browser/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]
