
name: Integration continuous

# Déclenche le workflow sur les push et pull requests vers la branche main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Définit les jobs du workflow
jobs:
  frontend-test:
    # Le job est exécuté sur une machine virtuelle Ubuntu
    runs-on: ubuntu-latest


    steps:
      # Checkout le code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configuration de Node.js (nécessaire pour Angular)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Installer les dépendances
      - name: Install dependencies
        run: |
          npm install

      # Lancer les tests
      - name: Run tests
        run: |
          npm run test

      # Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build et Push de l'image Docker sur Docker Hub
      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: razzak2007/plateforme-autoecole-frontend:latest
          no-cache: true
